# Generated by Django 4.1.13 on 2024-11-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollementmodel',
            name='enrollementDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
