# Generated by Django 4.1.13 on 2024-12-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_usermodel_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('titre_fon', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('description_fon', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('imageCourse', models.FileField(blank=True, default=None, null=True, upload_to='static/public')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10000000000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelID', models.CharField(default=None, max_length=1000)),
                ('title', models.CharField(default=None, max_length=1000)),
                ('title_fon', models.CharField(default=None, max_length=1000)),
                ('image', models.FileField(blank=True, default=None, null=True, upload_to='static/public/image')),
                ('audio', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('content', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('content_fon', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CategoriesModel',
        ),
        migrations.DeleteModel(
            name='CoursecontentModel',
        ),
        migrations.DeleteModel(
            name='CourseModel',
        ),
        migrations.DeleteModel(
            name='EnrollementModel',
        ),
        migrations.DeleteModel(
            name='QuizModel',
        ),
        migrations.DeleteModel(
            name='ResultModel',
        ),
        migrations.RemoveField(
            model_name='payementmodel',
            name='userId',
        ),
    ]
