# Generated by Django 4.1.13 on 2024-12-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_hotelmodel_roomsmodel_delete_categoriesmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelmodel',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomsmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10000000000, null=True),
        ),
    ]
