# Generated by Django 4.1.13 on 2024-12-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_hotelmodel_country_roomsmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelmodel',
            name='audio',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hotelmodel',
            name='town',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomsmodel',
            name='size',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='roomsmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=10000000000, null=True),
        ),
    ]
